### ISSUE TITLE
Serve files 

### ISSUE THREAD

**Issue by jpower432** [hauler-dev/hauler#13]
- [ ] #14 Collect files from directory, including sub directories
- [ ] #15 Develop copy package with oras
- [ ] #16 Populate file server with directory contents
