### ISSUE TITLE
Serve container images 

### ISSUE THREAD

**Issue by jpower432** [hauler-dev/hauler#4]
- [ ] #5 Collect images from image list file
- [ ] #6 Collect images from image archives
- [ ] #7 Deploy docker registry
- [ ] #8 Populate registry with all images
